version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.15

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v2-pkg-cache

      - run:
          name: GolangCI Linter
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
            golangci-lint run -v

      - run:
          name: Run unit tests
          command: |
            go get -u github.com/jstemmer/go-junit-report
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -cover -race -coverprofile=${TEST_RESULTS}/coverage.out -v $(go list ./...  | grep -v /vendor/) | tee ${TEST_RESULTS}/go-test.out

      - save_cache:
          key: v2-pkg-cache
          paths:
            - "/go/pkg"

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - test
